name: Continuous Integration

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  ci:
    strategy:
      matrix:
        buildType: [release, snapshot]
    uses: ./.github/workflows/build.yml
    with:
      buildType: ${{ matrix.buildType }}