name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    env:
      ProjectName: VivaldiCustomLauncher

    runs-on: windows-latest

    steps:
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Clone
      uses: actions/checkout@v3

    - name: Restore
      run: msbuild /p:Configuration=Release /t:restore

    - name: Build
      run: msbuild /p:Configuration=Release /t:build

    - name: Smoke test
      run: dotnet test Tests --filter DisplayName~SmokeTests --configuration Release --no-build --verbosity normal

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ProjectName }}
        path: ${{ env.ProjectName }}\bin\Release\*.exe
        if-no-files-found: error
