name: Smoke test latest Vivaldi

on:
  workflow_dispatch:
  schedule:
    - cron: '52 2/6 * * *'

env:
  BUILD_CONFIG: Debug

jobs:
  setup:
    runs-on: windows-latest
    steps:
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Clone
      uses: actions/checkout@v3

    - name: Read Vivaldi version of existing test data
      id: existing-test-data
      run: |
        $existingVersion = (Get-Content .\Tests\Data\vivaldi-version.txt -TotalCount 1).Trim()
        Out-File -InputObject "EXISTING_VERSION=$existingVersion" -FilePath $env:GITHUB_ENV -Append -Encoding UTF8 
        Write-Output "Repository's existing test data is from Vivaldi $existingVersion"

  install-vivaldi:
    uses: ./.github/workflows/install-vivaldi.yml

  update-test-data:
    runs-on: windows-latest
    needs: [setup, install-vivaldi]
    steps:
    - name: Compare existing and latest version numbers
      run: |
        $isUpToDate = $env:EXISTING_VERSION -eq '${{ needs.install-vivaldi.outputs.latest-version }}'
        Out-File -InputObject "UP_TO_DATE=$isUpToDate" -FilePath $env:GITHUB_ENV -Append -Encoding UTF8
        If ($isUpToDate) {
          Write-Output "::notice title=No Vivaldi update::Test data was already up-to-date with the latest Vivaldi version (${{ needs.install-vivaldi.outputs.latest-version }}). Not updating or testing."
        } Else {
          Write-Output "::notice title=Vivaldi update released::Test data version (${env:EXISTING_VERSION}) is lower than the latest Vivaldi version (${{ needs.install-vivaldi.outputs.latest-version }}). Updating test data and running smoke tests."
          Out-File -InputObject "### Updated to Vivaldi **${{ needs.install-vivaldi.outputs.latest-version }}**" -FilePath $env:GITHUB_STEP_SUMMARY -Append -Encoding UTF8 
        }

    - name: Copy installation files into test data
      # if: ${{ env.UP_TO_DATE != 'True' }}
      run: |
        Copy-Item -Force -Path @(`
          '.\vivaldi-installation\Application\*\resources\vivaldi\bundle.js',
          '.\vivaldi-installation\Application\*\resources\vivaldi\background-common-bundle.js'
        ) -Destination .\Tests\Data\BundleScript\
        Write-Output "Updated bundle.js and background-common-bundle.js in test data"
        
    - name: Update version number in test data
      # if: ${{ env.UP_TO_DATE != 'True' }}
      run: |
        Out-File -InputObject '${{ needs.install-vivaldi.outputs.latest-version }}' -FilePath .\Tests\Data\vivaldi-version.txt -Encoding UTF8 
        Write-Output "Marked test data as coming from Vivaldi ${{ needs.install-vivaldi.outputs.latest-version }}"
      
    - name: Commit and push new test data
      # if: ${{ env.UP_TO_DATE != 'True' }}
      uses: EndBug/add-and-commit@v9
      env:
        HOME: "~" # get rid of a benign warning
      with:
        add: ./Tests/Data
        message: Update test data for Vivaldi ${{ needs.install-vivaldi.outputs.latest-version }}
        pathspec_error_handling: exitImmediately
        author_name: Ben Hutchison
        author_email: ben@aldaviva.com
        committer_name: GitHub Actions
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com
        push: true

    - name: Restore solution
      # if: ${{ env.UP_TO_DATE != 'True' }}
      run: msbuild /p:Configuration=${{ env.BUILD_CONFIG }} -t:restore

    - name: Build solution
      # if: ${{ env.UP_TO_DATE != 'True' }}
      run: msbuild /p:Configuration=${{ env.BUILD_CONFIG }} -t:build

  smoke-test:
    uses: ./.github/workflows/smoke-test.yml
    needs: update-test-data
    with:
      build-config: ${{ env.BUILD_CONFIG }}